"use client";
import { useState } from "react";
import { Building2, Search, Plus, ChevronRight, X, Pencil, Mail, MessageCircle, SlidersHorizontal, CalendarClock, Lightbulb, LayoutGrid, List } from "lucide-react";
import { readCompanyProfile, readableContactNotes, type CompanyProfile } from "@/lib/companyProfile";
import type { ClientField } from "@/lib/clientFields";
import type { Contact } from "./ContactsClient";
import { ClientPanel } from "./ClientPanel";
export type Company = { id: string; name: string; sector: string | null; address: string | null; email: string | null; phone: string | null; notes: string | null; profile: string };
const control = "rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50";
const primary = "inline-flex items-center justify-center gap-2 rounded-lg bg-brand-800 px-4 py-2.5 text-sm font-semibold text-white hover:bg-brand-900 disabled:opacity-50";
const dateLabel = (date?: string | null) => date ? date.split("-").reverse().join("/") : "—";
const normalized = (text: string) => text.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLocaleLowerCase("fr");
function members(company: Company, contacts: Contact[]) { return contacts.filter((c) => c.companyId === company.id).sort((a,b) => Number(b.customValues?.custom_amone_contact_principal === "true") - Number(a.customValues?.custom_amone_contact_principal === "true") || a.name.localeCompare(b.name,"fr")); }
function profileOf(company: Company, contacts: Contact[]): CompanyProfile {
  const list = members(company,contacts), c = list[0];
  const value = (key: string) => c?.customValues?.[`custom_amone_${key}`] || "";
  const dates = list.map((c) => c.nextContactDate).filter(Boolean).sort();
  return { type: value("type_prospect") === "Club sportif amateur" ? "Club sportif amateur" : "Entreprise", priority: (["A","B","C"].includes(value("priorite")) ? value("priorite") : "") as CompanyProfile["priority"], status: "À contacter", potential: value("effectif_estime") || value("equipes_categories_licencies"), idea: value("angle_commercial_AMONE"), nextContactDate: dates[0] || null, followupNotes: "", ...readCompanyProfile(company.profile) };
}
export function StructuresBrowser({ contacts, companies, fields, loading, error, onReload, onFields, onContact }: { contacts: Contact[]; companies: Company[]; fields: ClientField[]; loading: boolean; error: string; onReload: () => Promise<void>; onFields: () => void; onContact: (contact: Contact | null, companyId?: string) => void }) {
  const [search,setSearch] = useState(""); const [filter,setFilter] = useState("ALL"); const [priority,setPriority] = useState(false); const [statusFilter,setStatusFilter] = useState("ALL"); const [grid,setGrid] = useState(false);
  const [selectedId,setSelectedId] = useState<string | null>(null); const [tab,setTab] = useState("resume"); const [edit,setEdit] = useState(false); const [creating,setCreating] = useState(false);
  const [draft,setDraft] = useState({name:"",sector:"",address:"",email:"",phone:""}); const [profile,setProfile] = useState<CompanyProfile>({}); const [baseline,setBaseline] = useState(""); const [busy,setBusy] = useState(false); const [saveError,setSaveError] = useState(""); const [message,setMessage] = useState("");
  const selected = companies.find((c) => c.id === selectedId); const people = selected ? members(selected,contacts) : [];
  const visible = (key: string) => fields.find((f) => f.id === key)?.enabled ?? true;
  const today = new Intl.DateTimeFormat("sv-SE",{timeZone:"Europe/Paris"}).format(new Date());
  const rows = companies.map((company) => ({company,profile:profileOf(company,contacts),people:members(company,contacts)}));
  const standalone = contacts.filter((c) => !c.companyId);
  const shown = rows.filter(({company,profile,people}) => (filter === "ALL" || filter === "CLUB" && profile.type === "Club sportif amateur" || filter === "COMPANY" && profile.type !== "Club sportif amateur" || filter === "DUE" && !!profile.nextContactDate && profile.nextContactDate <= today) && (!priority || profile.priority === "A") && (statusFilter === "ALL" || profile.status === statusFilter) && normalized([company.name,company.sector,...people.flatMap((c) => [c.name,c.email,c.phone,c.tags])].filter(Boolean).join(" ")).includes(normalized(search))).sort((a,b) => a.company.name.localeCompare(b.company.name,"fr"));
  function open(company?: Company) {
    setSelectedId(company?.id || null); setCreating(!company); setEdit(!company); setTab("resume"); setSaveError("");setMessage("");
    const d={name:company?.name || "",sector:company?.sector || "",address:company?.address || "",email:company?.email || "",phone:company?.phone || ""};const p=company?profileOf(company,contacts):{type:"Entreprise" as const,status:"À contacter" as const,priority:"" as const};setDraft(d);setProfile(p);setBaseline(JSON.stringify([d,p]));
  }
  function close() { if(busy)return;if(JSON.stringify([draft,profile])!==baseline&&!confirm("Fermer sans enregistrer les modifications ?"))return;setSelectedId(null);setCreating(false);setEdit(false); }
  function startEdit(){setEdit(true);setTab("resume");}
  async function save(e: React.FormEvent) {
    e.preventDefault();setBusy(true);setSaveError("");
    try { const res=await fetch(creating?"/api/crm/companies":`/api/crm/companies/${selectedId}`,{method:creating?"POST":"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({...draft,profile})});const data=await res.json();if(!res.ok)throw new Error(data.error === "Données invalides" ? "Vérifiez les champs et les dates." : data.error || "Enregistrement impossible.");await onReload();setSelectedId(data.id);setCreating(false);setEdit(false);setBaseline(JSON.stringify([draft,profile]));setMessage("Fiche enregistrée."); }catch(e){setSaveError(e instanceof Error?e.message:"Connexion impossible.");}finally{setBusy(false);}
  }
  function openPerson(person: Contact | null) { if(JSON.stringify([draft,profile])!==baseline&&!confirm("Quitter sans enregistrer le suivi ?"))return;setSelectedId(null);onContact(person,selected?.id); }
  const tabs=[['ALL','Toutes les structures',companies.length],['COMPANY','Entreprises',rows.filter((r)=>r.profile.type !== 'Club sportif amateur').length],['CLUB','Clubs sportifs',rows.filter((r)=>r.profile.type === 'Club sportif amateur').length],['DUE','À recontacter',rows.filter((r)=>r.profile.nextContactDate && r.profile.nextContactDate<=today).length]];
  function input(key: keyof typeof draft,label: string,type="text") { return <label className="block text-sm font-medium text-slate-700">{label}<input aria-label={label} required={key === "name"} maxLength={key === "name"?200:1000} type={type} value={draft[key]} onChange={(e)=>setDraft({...draft,[key]:e.target.value})} className="mt-1 w-full" /></label>; }
  return <div className="space-y-5">
    <header className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight">Clients & prospects</h1><p className="mt-2 text-sm text-slate-500">{companies.length} structures · {contacts.length} contacts réunis au même endroit.</p></div><div className="flex flex-wrap gap-2"><button onClick={onFields} className={`${control} inline-flex items-center gap-2`}><SlidersHorizontal className="h-4 w-4" />Gérer les champs</button><button onClick={()=>open()} className={primary}><Plus className="h-4 w-4" />Nouvelle structure</button><button onClick={()=>onContact(null)} className={control}>Nouveau contact</button></div></header>
    <div className="flex flex-wrap gap-x-5 gap-y-2 border-b border-slate-200">{tabs.map(([id,label,count])=><button key={id} onClick={()=>setFilter(String(id))} aria-pressed={filter===id} className={`flex items-center gap-2 border-b-2 py-3 text-sm ${filter===id?'border-brand-700 font-semibold text-brand-800':'border-transparent text-slate-500'}`}>{label}<span className="rounded bg-slate-100 px-1.5 py-0.5 text-xs text-slate-500">{count}</span></button>)}</div>
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center gap-2 p-4"><label className="flex min-w-[180px] flex-1 items-center gap-2 rounded-lg border border-slate-200 px-3 text-slate-400"><Search className="h-4 w-4" /><input aria-label="Rechercher une structure ou un contact" placeholder="Rechercher une structure, une personne, un email…" value={search} onChange={(e)=>setSearch(e.target.value)} className="w-full min-w-0 border-0 bg-transparent text-sm focus:ring-0" />{search&&<button onClick={()=>setSearch("")} aria-label="Effacer la recherche"><X className="h-4 w-4" /></button>}</label><button onClick={()=>setPriority(!priority)} aria-pressed={priority} className={`${control} ${priority?'border-brand-200 bg-brand-50 text-brand-800':''}`}>Priorité A</button><select aria-label="Filtrer par statut" value={statusFilter} onChange={(e)=>setStatusFilter(e.target.value)} className="text-sm"><option value="ALL">Tous les statuts</option>{['À contacter','Contacté','À relancer','Client','Sans suite'].map((s)=><option key={s}>{s}</option>)}</select><button aria-label={grid?'Afficher en liste':'Afficher en cartes'} onClick={()=>setGrid(!grid)} className={control}>{grid?<List className="h-4 w-4" />:<LayoutGrid className="h-4 w-4" />}</button></div>
    {error&&<p role="alert" className="px-5 pb-4 text-sm text-red-700">{error} <button onClick={()=>void onReload()} className="underline">Réessayer</button></p>}
    {!grid&&<div className="hidden grid-cols-[minmax(0,2fr)_1fr_80px_100px_60px_110px_16px] gap-3 border-y border-slate-200 bg-slate-50 px-5 py-3 text-xs text-slate-500 xl:grid"><span>Structure</span><span>Type</span><span>Priorité</span><span>Statut</span><span>Contacts</span><span>Relance</span><span /></div>}
    {loading?<p className="p-8 text-sm text-slate-500">Chargement…</p>:<div className={grid?'grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-3':''}>{shown.map(({company,profile,people})=><button key={company.id} onClick={()=>open(company)} className={grid?'space-y-4 rounded-xl border border-slate-200 p-5 text-left hover:bg-brand-50/40':"grid w-full grid-cols-[minmax(0,1fr)_auto] items-center gap-3 border-b border-slate-100 px-5 py-4 text-left last:border-0 hover:bg-brand-50/40 xl:grid-cols-[minmax(0,2fr)_1fr_80px_100px_60px_110px_16px]"}><div className="flex min-w-0 items-center gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-brand-50 text-brand-700"><Building2 className="h-4 w-4" /></span><div className="min-w-0"><p className="truncate text-sm font-semibold">{company.name}</p><p className="mt-1 truncate text-xs text-slate-500">{company.sector || 'Activité à préciser'}</p></div></div><span className="text-xs text-slate-500">{profile.type==='Club sportif amateur'?'Club sportif':profile.type}</span><span className="w-fit rounded-md bg-brand-50 px-2 py-1 text-xs text-brand-800">{profile.priority?`Priorité ${profile.priority}`:'—'}</span><span className="text-xs text-slate-500">{profile.status}</span><span className="text-xs text-slate-500">{people.length}{grid?' contacts':''}</span><span className="text-xs text-slate-500">{dateLabel(profile.nextContactDate)}</span>{!grid&&<ChevronRight className="h-4 w-4 text-slate-400" />}</button>)}{!shown.length&&!error&&<p className="p-10 text-center text-sm text-slate-500">{companies.length?'Aucune structure pour ces filtres.':'Ajoutez une structure ou un premier contact.'}</p>}</div>}
    <footer className="flex flex-wrap justify-between gap-2 border-t border-slate-100 px-5 py-3 text-xs text-slate-500"><span>{shown.length} structures affichées</span><span>{companies.length} structures · {contacts.length} contacts</span></footer></section>
    {standalone.length>0&&<section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-semibold">Contacts sans structure ({standalone.length})</h2><div className="mt-3 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{standalone.filter((c)=>normalized([c.name,c.email,c.phone].join(' ')).includes(normalized(search))).map((c)=><button key={c.id} onClick={()=>onContact(c)} className="rounded-lg border border-slate-100 p-3 text-left hover:bg-brand-50"><span className="block text-sm font-medium">{c.name}</span><span className="text-xs text-slate-500">{c.email||c.phone||'Coordonnées à compléter'}</span></button>)}</div></section>}
    {(selected||creating)&&<ClientPanel title={creating?'Nouvelle structure':selected!.name} onClose={close}><form onSubmit={save} className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-500">{profile.type} {selected?.sector?`· ${selected.sector}`:''}</p>{!creating&&!edit&&<button type="button" onClick={startEdit} className={`${control} inline-flex items-center gap-2`}><Pencil className="h-4 w-4" />Modifier la fiche</button>}</div>
    {!edit&&<div role="tablist" aria-label="Rubriques de la structure" className="flex gap-6 border-b border-slate-200">{[['resume','Résumé'],['contacts',`Contacts (${people.length})`],['suivi','Suivi']].map(([id,label])=><button key={id} type="button" role="tab" aria-selected={tab===id} onClick={()=>setTab(id)} className={`border-b-2 pb-3 text-sm ${tab===id?'border-brand-700 font-semibold text-brand-800':'border-transparent text-slate-500'}`}>{label}</button>)}</div>}
    {message&&<p role="status" className="text-sm text-brand-700">{message}</p>}
    <fieldset disabled={busy} className="space-y-5">
    {edit?<><div className="grid gap-3 sm:grid-cols-2">{input('name','Nom de la structure')}{input('sector','Activité / sport')}{input('email','Email général','email')}{input('phone','Téléphone général')}</div>{input('address','Adresse de la structure')}<div className="grid gap-3 sm:grid-cols-2"><label className="block text-sm">Type<select aria-label="Type de structure" value={profile.type||'Entreprise'} onChange={(e)=>setProfile({...profile,type:e.target.value as CompanyProfile['type']})} className="mt-1 w-full">{['Entreprise','Club sportif amateur','Autre'].map((s)=><option key={s}>{s}</option>)}</select></label><label className="block text-sm">Priorité<select aria-label="Priorité" value={profile.priority||''} onChange={(e)=>setProfile({...profile,priority:e.target.value as CompanyProfile['priority']})} className="mt-1 w-full"><option value="">Non définie</option>{['A','B','C'].map((s)=><option key={s}>{s}</option>)}</select></label></div><label className="block text-sm">Effectif / potentiel<input aria-label="Effectif / potentiel" value={profile.potential||''} maxLength={1000} onChange={(e)=>setProfile({...profile,potential:e.target.value})} className="mt-1 w-full" /></label><label className="block text-sm">Idée de proposition AMONĒ<textarea aria-label="Idée de proposition AMONĒ" rows={3} maxLength={2000} value={profile.idea||''} onChange={(e)=>setProfile({...profile,idea:e.target.value})} className="mt-1 w-full" /></label></>:
    tab==='resume'?<><div className="flex items-center gap-3"><span className="rounded-md bg-brand-50 px-3 py-1 text-xs text-brand-800">{profile.priority?`Priorité ${profile.priority}`:'Priorité à définir'}</span><span className="text-sm text-slate-500">{profile.status}</span><span className="ml-auto text-xs text-slate-500">{people.length} contacts</span></div>{profile.potential&&<section className="border-b border-slate-200 pb-5"><h3 className="text-sm font-semibold">Ce qu’il faut retenir</h3><p className="mt-2 text-sm text-slate-600">{profile.potential}</p><p className="mt-1 text-xs text-slate-400">Informations publiées à reconfirmer lors du contact.</p></section>}{profile.idea&&<section className="rounded-xl bg-brand-50 p-5"><h3 className="flex items-center gap-2 text-sm font-semibold text-brand-800"><Lightbulb className="h-4 w-4" />Une piste pour AMONĒ</h3><p className="mt-2 text-sm leading-relaxed text-slate-600">{profile.idea}</p></section>}<section className="space-y-2"><h3 className="text-sm font-semibold">Coordonnées de la structure</h3>{visible('address')&&<p className="text-sm text-slate-600">{selected?.address||'Adresse à compléter'}</p>}<div className="flex flex-wrap gap-2">{visible('email')&&selected?.email&&<a href={`mailto:${selected.email}`} className={`${control} inline-flex items-center gap-2`}><Mail className="h-4 w-4" />{selected.email}</a>}{visible('phone')&&selected?.phone&&<p className="text-sm text-slate-500">{selected.phone}</p>}</div></section><details className="border-t border-slate-200 pt-4"><summary className="cursor-pointer text-sm font-medium text-slate-500">Sources & informations détaillées</summary><dl className="mt-4 grid gap-4 sm:grid-cols-2">{fields.filter((f)=>f.custom&&f.enabled&&people[0]?.customValues?.[f.id]).map((f)=><div key={f.id}><dt className="text-xs text-slate-500">{f.label}</dt><dd className="mt-1 break-words text-sm text-slate-700">{f.type==='CHECKBOX'?(people[0].customValues[f.id]==='true'?'Oui':'Non'):people[0].customValues[f.id]}</dd></div>)}</dl>{selected?.notes&&<details className="mt-4"><summary className="cursor-pointer text-xs text-slate-500">Données d’origine conservées</summary><p className="mt-3 whitespace-pre-wrap break-words text-xs text-slate-500">{selected.notes}</p></details>}</details></>:
    tab==='contacts'?<><div className="flex justify-end"><button type="button" onClick={()=>openPerson(null)} className={control}>+ Ajouter un contact</button></div>{people.map((c)=><article key={c.id} className="rounded-xl border border-slate-200 p-5"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="text-sm font-semibold">{c.name}</h3>{visible('role')&&<p className="mt-1 text-sm text-slate-500">{c.role||'Fonction à préciser'}</p>}</div>{c.customValues?.custom_amone_contact_principal==='true'&&<span className="h-fit rounded-md bg-brand-50 px-2 py-1 text-xs text-brand-800">Principal</span>}</div><div className="mt-3 space-y-1 text-sm text-slate-600">{visible('email')&&c.email&&<p className="break-words">{c.email}</p>}{visible('phone')&&c.phone&&<p>{c.phone}</p>}</div>{visible('notes')&&readableContactNotes(c.notes)&&<p className="mt-3 text-xs leading-relaxed text-slate-500">{readableContactNotes(c.notes)}</p>}<div className="mt-4 flex flex-wrap gap-2">{visible('email')&&c.email&&<a href={`mailto:${c.email}`} className={`${control} inline-flex items-center gap-2`}><Mail className="h-4 w-4" />Mail</a>}{visible('phone')&&c.phone&&<a href={`https://wa.me/${international(c.phone)}`} target="_blank" rel="noopener noreferrer" className={`${control} inline-flex items-center gap-2`}><MessageCircle className="h-4 w-4" />WhatsApp</a>}<button type="button" onClick={()=>openPerson(c)} className={`${control} inline-flex items-center gap-2`}><Pencil className="h-4 w-4" />Modifier</button></div>{c.customValues?.custom_amone_whatsapp_potentiel?.startsWith('À vérifier')&&<p className="mt-3 text-xs text-slate-400">WhatsApp à vérifier — mobile professionnel publié.</p>}{c.customValues?.custom_amone_opt_out==='true'&&<p className="mt-3 text-xs font-medium text-red-700">Opposition aux communications enregistrée.</p>}</article>)}{!people.length&&<p className="text-sm text-slate-500">Ajoutez votre premier interlocuteur.</p>}</>:null}
    {(tab==='suivi'||edit)&&<section className="space-y-4"><h3 className="flex items-center gap-2 text-sm font-semibold"><CalendarClock className="h-4 w-4" />Suivi de la structure</h3><label className="block text-sm">Statut<select aria-label="Statut de prospection" value={profile.status||'À contacter'} onChange={(e)=>setProfile({...profile,status:e.target.value as CompanyProfile['status']})} className="mt-1 w-full">{['À contacter','Contacté','À relancer','Client','Sans suite'].map((s)=><option key={s}>{s}</option>)}</select></label><div className="grid gap-3 sm:grid-cols-2">{(['lastContactDate','nextContactDate'] as const).map((key)=><label key={key} className="block text-sm">{key==='lastContactDate'?'Dernier échange':'Prochaine relance'}<input aria-label={key==='lastContactDate'?'Dernier échange':'Prochaine relance'} type="date" value={profile[key]||''} onChange={(e)=>setProfile({...profile,[key]:e.target.value||null})} className="mt-1 w-full" /></label>)}</div><label className="block text-sm">Note de suivi<textarea aria-label="Note de suivi" rows={4} maxLength={10000} placeholder="Interlocuteur, réponse, prochaine étape…" value={profile.followupNotes||''} onChange={(e)=>setProfile({...profile,followupNotes:e.target.value})} className="mt-1 w-full" /></label></section>}
    </fieldset>{saveError&&<p role="alert" className="text-sm text-red-700">{saveError}</p>}{(edit||tab==='suivi')&&<footer className="flex justify-end gap-3 border-t border-slate-200 pt-4"><button type="button" disabled={busy} onClick={close} className={control}>Fermer</button><button disabled={busy} className={primary}>{busy?'Enregistrement…':'Enregistrer'}</button></footer>}</form></ClientPanel>}
  </div>;
}
function international(phone: string){const number=phone.replace(/[^0-9]/g,'');return number.startsWith('00')?number.slice(2):/^0[1-9]\d{8}$/.test(number)?'33'+number.slice(1):number;}
