"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ClientPanel } from "../../clients/contacts/ClientPanel";
import { Search, ArrowLeft, ExternalLink, Mail, Pencil } from "lucide-react";
type Partner={id:string;sourceId:string;name:string;type:string;profile:Record<string,string>;status:string;lastContactDate:string|null;nextContactDate:string|null;optOut:boolean;notes:string};
const statuses=["À contacter","Contacté","À relancer","En discussion","Partenariat validé","Sans suite"];
const control="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-4 py-2 text-sm";
const summaryKeys=["Ville / ancrage déclaré","Tournage Nice / mobilité","Secteur / niche","Formats proposés / à valider","Objectif AMONĒ","Angle commercial AMONĒ à explorer"];
const qualificationKeys=["Abonnés vérifiés actuels","Engagement vérifié","Part audience Nice vérifiée","Tarif négocié","Notes / qualification restante","Source(s)","Date vérification documentaire"];
const socialKeys=["Instagram","LinkedIn","Site / portfolio / fiche","URL contact"];
function safeLink(value:string){try{const u=new URL(value);return ['http:','https:','mailto:'].includes(u.protocol)?u.href:null;}catch{return null;}}
export function MarketingPartners(){
 const [items,setItems]=useState<Partner[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const [search,setSearch]=useState(""),[type,setType]=useState("ALL"),[priority,setPriority]=useState(false),[due,setDue]=useState(false);
 const [draft,setDraft]=useState<Partner|null>(null),[baseline,setBaseline]=useState(""),[tab,setTab]=useState("resume"),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function load(){setLoading(true);try{const r=await fetch('/api/marketing/partners');if(!r.ok)throw Error('Impossible de charger les partenaires.');setItems(await r.json());setError('');}catch(e){setError(e instanceof Error?e.message:'Connexion impossible.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 function open(p:Partner){const next={...p,profile:{...p.profile}};setDraft(next);setBaseline(JSON.stringify(next));setTab('resume');setEditing(false);setMessage('');}
 function close(){if(busy)return;if(draft&&JSON.stringify(draft)!==baseline&&!confirm('Fermer sans enregistrer les modifications ?'))return;setDraft(null);}
 function field(key:string,value:string){if(draft)setDraft({...draft,profile:{...draft.profile,[key]:value}});}
 async function save(e:React.FormEvent){e.preventDefault();if(!draft)return;setBusy(true);setMessage('');try{const r=await fetch('/api/marketing/partners/'+draft.id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)});const p=await r.json();if(!r.ok)throw Error(p.error==='Données invalides'?'Vérifiez le nom et les dates.':p.error);setDraft(p);setBaseline(JSON.stringify(p));setEditing(false);setItems(prev=>prev.map(i=>i.id===p.id?p:i));setMessage('Fiche enregistrée.');}catch(e){setMessage(e instanceof Error?e.message:'Enregistrement impossible.');}finally{setBusy(false);}}
 const today=new Date().toLocaleDateString('en-CA');
 const filtered=items.filter(p=>(type==='ALL'||p.type===type)&&(!priority||p.profile['Priorité']==='A')&&(!due||!!p.nextContactDate&&p.nextContactDate<=today)&&[p.name,...Object.values(p.profile)].join(' ').toLocaleLowerCase('fr').includes(search.toLocaleLowerCase('fr')));
 function details(keys:string[]){return <dl className="grid gap-5 sm:grid-cols-2">{keys.map(k=><div key={k}><dt className="text-xs text-slate-500">{k}</dt><dd className="mt-2 whitespace-pre-wrap break-words text-sm leading-relaxed">{draft?.profile[k]||'À renseigner'}</dd></div>)}</dl>;}
 return <div className="space-y-6"><Link href="/marketing" className="inline-flex items-center gap-2 text-sm text-slate-500"><ArrowLeft className="h-4 w-4"/>Calendrier marketing</Link><div><h1 className="text-3xl">Partenaires & créateurs</h1><p className="mt-2 text-sm text-slate-500">{items.length} profils pour créer du contenu et faire connaître AMONĒ.</p></div><div className="flex flex-wrap gap-2">{['ALL','UGC','Créateur / influenceur'].map(t=><button key={t} onClick={()=>setType(t)} aria-pressed={type===t} className={`${control} ${type===t?'bg-brand-50 text-brand-700':''}`}>{t==='ALL'?'Tous les profils':t} · {items.filter(p=>t==='ALL'||p.type===t).length}</button>)}</div><div className="flex flex-wrap gap-3 rounded-xl bg-white p-4"><label className="flex min-w-0 flex-1 items-center gap-2"><Search className="h-4 w-4 text-slate-400"/><input className="w-full" aria-label="Rechercher un partenaire" placeholder="Nom, niche, ville…" value={search} onChange={e=>setSearch(e.target.value)}/></label><button aria-pressed={priority} onClick={()=>setPriority(!priority)} className={`${control} ${priority?'text-brand-700 bg-brand-50':''}`}>Priorité A</button><button aria-pressed={due} onClick={()=>setDue(!due)} className={`${control} ${due?'text-brand-700 bg-brand-50':''}`}>À recontacter</button></div>{error&&<p role="alert" className="text-red-700">{error}<button onClick={load} className={control}>Réessayer</button></p>}{loading?<p>Chargement…</p>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(p=><button key={p.id} onClick={()=>open(p)} className="rounded-xl border border-slate-100 bg-white p-5 text-left shadow-sm hover:border-brand-200"><div className="mb-4 flex justify-between gap-2"><span className="text-xs text-slate-500">{p.type}</span><span className="rounded-md bg-brand-50 px-2 py-1 text-xs text-brand-700">Priorité {p.profile['Priorité']||'—'}</span></div><h2 className="text-base font-semibold">{p.name}</h2><p className="mt-2 text-sm text-slate-500">{p.profile['Secteur / niche']}</p><p className="mt-3 text-xs text-slate-500">{p.profile['Ville / ancrage déclaré']}</p><div className="mt-4 flex flex-wrap justify-between gap-2 border-t border-slate-100 pt-3 text-xs"><span>{p.optOut?'Ne plus contacter':p.status}</span><span>{p.nextContactDate?'Relance : '+p.nextContactDate:'À qualifier'}</span></div></button>)}{!filtered.length&&<p className="p-5 text-sm text-slate-500">Aucun profil pour ces filtres.</p>}</div>}
 {draft&&<ClientPanel breadcrumb="Marketing / Partenaires" title={draft.name} onClose={close}><form onSubmit={save} className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-500">{draft.type} · {draft.status}</p><button type="button" className={control} onClick={()=>setEditing(!editing)}><Pencil className="h-4 w-4"/>{editing?'Voir la fiche':'Modifier la fiche'}</button></div>{draft.optOut&&<p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">Ne plus contacter : opposition enregistrée.</p>}
 <div role="tablist" aria-label="Rubriques du partenaire" className="flex gap-5 border-b border-slate-200">{[['resume','Résumé'],['qualification','Qualification'],['suivi','Suivi']].map(([id,label])=><button key={id} type="button" role="tab" aria-selected={tab===id} onClick={()=>setTab(id)} className={`border-b-2 pb-3 text-sm ${tab===id?'border-brand-600 text-brand-700':'border-transparent text-slate-500'}`}>{label}</button>)}</div>
 <fieldset disabled={busy} className="space-y-5">{editing?<><label className="block text-sm">Nom / compte<input aria-label="Nom / compte" required maxLength={200} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} className="mt-1 w-full"/></label><label className="block text-sm">Type<select aria-label="Type de partenaire" value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value})} className="mt-1 w-full"><option>UGC</option><option>Créateur / influenceur</option></select></label><div className="grid gap-4 sm:grid-cols-2">{Object.keys(draft.profile).filter(k=>!['ID','Partie CRM','Nom / compte','Type prospect','Statut','Dernier contact','Prochaine relance','Opt-out / ne plus contacter'].includes(k)).map(k=><label key={k} className="block text-xs text-slate-500">{k}<textarea aria-label={k} rows={draft.profile[k]?.length>100?3:1} maxLength={10000} value={draft.profile[k]} onChange={e=>field(k,e.target.value)} className="mt-1 w-full"/></label>)}</div></>:tab==='resume'?<><div className="flex flex-wrap gap-2">{!draft.optOut&&draft.profile['Email public']&&<a href={'mailto:'+draft.profile['Email public']} className={control}><Mail className="h-4 w-4"/>Mail</a>}{socialKeys.map(k=>{const href=safeLink(draft.profile[k]);return href?<a key={k} href={href} target="_blank" rel="noreferrer" className={control}><ExternalLink className="h-4 w-4"/>{k==='URL contact'?'Contacter / formulaire':k==='Site / portfolio / fiche'?'Portfolio':k}</a>:null;})}</div>{details(['Contact principal','Fonction','Email public','Mobile professionnel publié','Téléphone',...summaryKeys])}<p className="rounded-lg bg-brand-50 p-4 text-xs leading-relaxed text-slate-600">Les angles sont des pistes à discuter. Disponibilité, audience locale, formats et droits restent à confirmer. Un profil UGC produit du contenu ; une diffusion auprès de sa communauté se négocie séparément.</p></>:tab==='qualification'?<>{details(qualificationKeys)}<details className="border-t pt-4"><summary className="cursor-pointer text-sm text-slate-500">Toutes les informations d’origine</summary><div className="mt-4">{details(Object.keys(draft.profile))}</div></details></>:null}
 {(editing||tab==='suivi')&&<section className="space-y-4"><label className="block text-sm">Statut<select aria-label="Statut du partenaire" value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})} className="mt-1 w-full">{statuses.map(s=><option key={s}>{s}</option>)}</select></label><div className="grid gap-3 sm:grid-cols-2">{(['lastContactDate','nextContactDate'] as const).map(k=><label key={k} className="block text-sm">{k==='lastContactDate'?'Dernier contact':'Prochaine relance'}<input aria-label={k==='lastContactDate'?'Dernier contact':'Prochaine relance'} type="date" value={draft[k]||''} onChange={e=>setDraft({...draft,[k]:e.target.value||null})} className="mt-1 w-full"/></label>)}</div><label className="block text-sm">Note de suivi<textarea aria-label="Note de suivi" rows={4} maxLength={10000} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})} className="mt-1 w-full"/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={draft.optOut} onChange={e=>setDraft({...draft,optOut:e.target.checked})}/>Ne plus contacter</label></section>}</fieldset>{message&&<p role="status" className="text-sm">{message}</p>}{(editing||tab==='suivi')&&<footer className="flex justify-end"><button disabled={busy} className="rounded-full bg-brand-600 px-5 py-2 text-sm text-white">{busy?'Enregistrement…':'Enregistrer'}</button></footer>}</form></ClientPanel>}
 </div>;
}
